# Generated by Django 5.2.4 on 2025-09-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_alter_evenement_image_alter_imageevenement_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='description_lieu',
        ),
        migrations.AlterField(
            model_name='evenement',
            name='titre',
            field=models.CharField(max_length=255),
        ),
    ]
