# Generated by Django 5.2.4 on 2025-07-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_consulte_favoris_note_recherche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='imageProfil',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_images/'),
        ),
    ]
